services:
  app:
    build:
      context: .
    container_name: safesignal-app
    ports:
      - "8080:8080"
    networks:
      - safesignal-net
    depends_on:
      - db
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/SafeSignalDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
  db:
    image: postgres:16-alpine
    container_name: safesignal-db
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - safesignal-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=SafeSignalDB
volumes:
  db_data:
networks:
  safesignal-net:
    name: safesignal-net
